### ISSUE TITLE
🖼️ Images - Assets not displayed when running `pnpm start`

### ISSUE THREAD

**Issue by ncn-ssw** [tinacms/tina-cloud-starter#542]
When connected to TinaCloud using `pnpm start`, images are not displayed during editing as they are being pulled from the Media Manager.

![Image](https://github.com/user-attachments/assets/4add534e-fc93-4779-96bf-940a937b1c52)  
**Figure: The Tina Starter with no image**

## Tasks

- [x] Correct mangling of image URLs
- [x] Improve instructions on how to set up the start with TinaCloud such that they include directions on how to setup media manager.

**Comment by ncn-ssw** [comment]
This problem appears to be related to https://github.com/tinacms/tinacms/issues/4801

- [ ] Ensure https://github.com/tinacms/tinacms/issues/4801 is closed upon completion of this item

**Comment by ncn-ssw** [comment]
I have still not determined the root cause yet.

- Testing with TinaCloud back to the merging of https://github.com/tinacms/tinacloud/pull/2105 indicates that the issue existed as far back as 19 July 2024 (2 months ago).
- The existence of https://github.com/tinacms/tinacms/issues/4465 suggests the bug may have been present as of March 2024
- So far, the only operation producing the full URL I can find is at https://github.com/tinacms/tinacms/blob/2762994587c1b97bdd8c188da70b1f8532d5da4a/packages/tinacms/src/toolkit/core/media-store.default.ts#L181

I intend to continue the investigation Monday 23 September 2024.

**Comment by JackDevAU** [comment]
Hey @ncn-ssw 

Also noticed this issue, I believe this to be due to the `next.config.js` file only allowing `https` connections to those 3rd party urls. 

To fix this we can change the `remotePatterns` from, 

```js
 images: {
    remotePatterns: [
      {
        protocol: "https",
        hostname: "assets.tina.io",
        port: "",
      },
    ],
  },
```

To

 ```js
images: {
    remotePatterns: [
      {
        hostname: "assets.tina.io",
      },
      {
        hostname: "unsplash.com",
      },
    ],
  },```

**Comment by JackDevAU** [comment]
Could be related to https://github.com/tinacms/tinacms/issues/4817

**Comment by ncn-ssw** [comment]
A fix by @kldavis4 has been deployed to TinaCloud to ensure that images are stored at the locations given by the original image URLs.

If you experience this issue, resync your media - your media will be placed in the correct locations.

![Image](https://github.com/user-attachments/assets/6639a2d1-d87b-4245-ae5e-6d718a9b86bc)
**Figure: Location of the "Resync Media" button within a Project on the Media tab**

**Comment by ncn-ssw** [comment]
PBI to be raised to enable media management automatically when using the TinaCloud Starter template.

**Comment by ncn-ssw** [comment]
✅ Done - PBI that was raised -
https://github.com/tinacms/tinacms/issues/5166

**Comment by ncn-ssw** [comment]
> This problem appears to be related to [tinacms/tinacms#4801](https://github.com/tinacms/tinacms/issues/4801)
> 
> * [x]  Ensure [🐛 Tina cloud - Some images are not found #2159 tinacms#4801](https://github.com/tinacms/tinacms/issues/4801) is closed upon completion of this item

To be closed by author of issue when happy.
